name: Manual Update
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses : actions/checkout@v2
    - name : Setup Python
      uses : actions/setup-python@v2
      with : 
        python-version : "3.8"

    - name : Install Dependencies
      run : |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name : Run AtCoder AutoClone
      run : |
        python src/init_exec.py
    
    - name : Commit and Push
      run : |
        git config user.name "ac auto clone bot"
        git config user.email "acautoclone@bot.com"
        git add .
        git commit -m "Added my codes from AtCoder"
        git pull
        git push origin main
        